language: clojure
lein: 2.8.1
sudo: false
node_js:
  - "8"
jdk:
  - oraclejdk8
script:
  - lein with-profile +cljs cljsbuild test publisher
  - lein with-profile 1.8 test
  - lein cloverage --codecov
after_success:
 - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
