language: clojure
lein: 2.9.6
sudo: false
node_js:
  - "16"
jdk:
  - oraclejdk11
script:
  - lein with-profile +cljs cljsbuild test run
  - lein cloverage --codecov
after_success:
 - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
