language: clojure
lein: 2.8.1
node_js:
  - "8"
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
script:
  - lein cljsbuild test publisher
  - lein cloverage --codecov
after_success:
 - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
